version: "3.9"
name: symfony-demo

services:
  php.service:
    container_name: symfony-demo_php
    build:
      context: .
      dockerfile: docker/dockerfile

  nginx.service:
    container_name: symfony-demo_nginx
    image: nginx:stable-alpine
    ports:
      - "8080:80"
    volumes:
      - ./app/public:/var/www/html/public
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php.service
