FROM php:7.1-fpm-alpine

ARG USERNAME=www-data
ARG GROUPNAME=www-data
ARG NEW_GROUP_ID=1000

RUN if getent passwd ${USERNAME} > /dev/null; then deluser ${USERNAME}; fi &&\
    if getent group ${GROUPNAME} > /dev/null; then delgroup ${GROUPNAME}; fi &&\
    addgroup -g ${NEW_GROUP_ID} ${GROUPNAME} &&\
    adduser -D -G ${GROUPNAME} ${USERNAME}

RUN wget https://getcomposer.org/download/latest-2.2.x/composer.phar -O /usr/local/bin/composer && chmod +x /usr/local/bin/composer

COPY docker/php.ini /usr/local/etc/php/conf.d/php.ini
COPY app /var/www/html
RUN chown -R ${USERNAME}:${GROUPNAME} /var/www/html

WORKDIR /var/www/html
USER ${USERNAME}

# symfony/flex <1.17 is abandoned. Override with newer version
# Fix dependencies issue with symfony/orm-pack
RUN composer config allow-plugins.symfony/flex true
RUN composer req symfony/flex:^1.17 \
    symfony/orm-pack:^2.0

# symfony/phpunit-bridge still can't fetch phpunit v5
RUN composer req --dev symfony/phpunit-bridge:^4.0
