FROM php:7.3-fpm-alpine

ARG USERNAME=www-data
ARG GROUPNAME=www-data
ARG NEW_GROUP_ID=1000

RUN if getent passwd ${USERNAME} > /dev/null; then deluser ${USERNAME}; fi &&\
    if getent group ${GROUPNAME} > /dev/null; then delgroup ${GROUPNAME}; fi &&\
    addgroup -g ${NEW_GROUP_ID} ${GROUPNAME} &&\
    adduser -D -G ${GROUPNAME} ${USERNAME}

RUN apk add --update --no-cache $PHPIZE_DEPS

RUN apk add --no-cache icu-dev \
    && docker-php-ext-install intl

RUN wget https://getcomposer.org/composer-stable.phar -O /usr/local/bin/composer && chmod +x /usr/local/bin/composer

COPY app /var/www/html
RUN chown -R ${USERNAME}:${GROUPNAME} /var/www/html

WORKDIR /var/www/html
USER ${USERNAME}

# symfony/flex <1.17 is abandoned. Override with newer version
RUN composer config allow-plugins.symfony/runtime true
RUN composer config allow-plugins.symfony/flex true
RUN composer req symfony/flex:^1.17
